### ISSUE TITLE
关于repre中的graphconv

### ISSUE THREAD

**Issue by WindLWQ** [THU-KEG/HIF-KAT#2]
请问论文中的哪个部分使用到了图卷积的操作呢？

**Comment by TranSirius** [comment]
Question: What's the utility of the graphconv operator in repre.py

Hi,

Thanks for your interest in our work!

In fact, the graph convolutional operation was not adopt in our paper. 
We attempted to integrate information from multiple closely related entities, such as entities accessed by the same person during a small time period. However, experimental results show that it does not work as we expected. 
As these are the codes for the research purpose, we do not remove these redundant code blocks, such as the graphconv operation.

As you may notice, direct running our codes will not call the graphconv function.


Best regards!


非常感谢你对我们工作的关注！

事实上，这是我们在研究早期做的一系列尝试，利用图卷积操作来对相关的实体信息做进一步的聚合，例如聚合经常在短时间内被同一个人访问的实体。但实验结果不甚理想，有可能是我们没有非常高质量的实体访问数据，此外，除了淘宝数据集以外，我们也没有办法拿到开源数据集的这类信息，所以在论文中没有使用到 graphconv。

由于这是我们研究目的的代码，所以其中可能包含了不少冗余的代码块。直接按 README 运行不会掉用到这个函数。
如果你有类似的实体共现信息数据，也不妨可以尝试一下对他们聚合

**Comment by WindLWQ** [comment]
感谢回答！
还有一个问题想冒昧提问一下，关于论文中对对Magellan的使用，是通过py_stringsimjoin包来实现的吗？

**Comment by TranSirius** [comment]
关于 Baseline 中 Magellan 的使用，我们是用 py_entitymatching 这个包来实现的，具体可以参考他们的文档：
http://anhaidgroup.github.io/py_entitymatching/v0.4.0/index.html

我在编写代码的时候很大程度上参考了他们 colab 上发布的代码：
http://anhaidgroup.github.io/py_entitymatching/v0.4.0/user_manual/guides.html#a-quick-tour-of-jupyter-notebook
