### ISSUE TITLE
Why not divide by "self.q_dim.sqrt()"

### ISSUE THREAD

**Issue by xufengnian222** [THU-KEG/HIF-KAT#3]
https://github.com/THU-KEG/HIF-KAT/blob/8b7d0c5f94975f505326ef8d373a761249fb5fc2/1-HRF-xgb/repre/attention.py#L104

in Transformer:
![image](https://user-images.githubusercontent.com/81036160/209423729-b2d667a2-e27d-4e43-9c3f-61c290124f3a.png)

**Comment by TranSirius** [comment]
In fact, the dimension of the query vectors is equal to the dimension of the key vectors, which means `q_dim = k_dim`
